### ISSUE TITLE
Multi-arch / ARM builds

### ISSUE THREAD

**Issue by ciaranmcnulty** [wiremock/wiremock-docker#44]
Cloning the repo and building seems to work fine (Apple Silicon) - it'd be great to build the images as multi-arch

**Comment by rodolpheche** [comment]
ARM is now supported : 6e062ef6418396997ba2d53e7111c1df8396af85

**Comment by afranken** [comment]
@rodolpheche 
Thanks for adding this - on Docker-hub, currently only `main` and `nightly` are pushed as multi-plattform.
Are you planning to do so as well for the upcoming releases, i.e. 2.32.0? :)

**Comment by rodolpheche** [comment]
@afranken 
Yes, upcoming releases will be multi-arch
