### ISSUE TITLE
WireMock version in wiremock:2.32.0 is 2.31.0

### ISSUE THREAD

**Issue by danielimre** [wiremock/wiremock-docker#46]
The WireMock standalone version in the released wiremock/wiremock:2.32.0 image is actually 2.31.0.
This issue also affects wiremock/wiremock:2.32.0-alpine.

See https://hub.docker.com/layers/wiremock/wiremock/2.32.0/images/sha256-5a889e25d17b0475780498b7b38d5a4c35333cd094cd3b4b301f18739549dc48?context=explore

**Comment by rodolpheche** [comment]
Thanks for your report.

A new version has been released to fix this issue.
You can now use the version [2.32.0-1](https://hub.docker.com/layers/wiremock/wiremock/2.32.0-1/images/sha256-302e1bc6981242b3c068a33868979b505e2e819160e23b914289d3639a912462?context=explore)
