### ISSUE TITLE
Incorrect Version of Wiremock in Docker Images

### ISSUE THREAD

**Issue by grburr** [wiremock/wiremock-docker#50]
I noticed with some of the current Docker image releases that the documentation refers to Wiremock version 2.33.x but the images appear to still use version 2.32. I noticed that the Dockerfile and image layers have `ENV WIREMOCK_VERSION 2.32.0` set. There are a number of security issues in sub libraries that the 2.33.x version of wiremock fixes. Could somebody take a look a re-release if the above is correct. Thanks

**Comment by rodolpheche** [comment]
Thanks for the report.
I just fixed the issue and deployed a newer version of the docker image : 2.33.1-1
