### ISSUE TITLE
2.32.0 missing SLF4J implementation

### ISSUE THREAD

**Issue by ascopes** [wiremock/wiremock-docker#51]
It appears both the debian-based and alpine-based container images are missing an SLF4J logger implementation on the classpath.

I understand that the non-standalone JAR of WireMock does not contain an implementation of SLF4J, but that the standalone JAR should. I assume the standalone JAR should be the one being used in this image, so I am not _entirely_ sure what is going on.

### Debian

1. Run `docker run -it --rm wiremock/wiremock:2.32.0 --verbose`
2. Observe the error in the output:

```
$ docker run --rm -it wiremock/wiremock:2.32.0 --verbose

2022-06-07 17:11:03.371 Verbose logging enabled
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-06-07 17:11:04.138 Verbose logging enabled
 /$$      /$$ /$$                     /$$      /$$                     /$$
| $$  /$ | $$|__/                    | $$$    /$$$                    | $$
| $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
| $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
| $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/
| $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$
| $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
|__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/

port:                         8080
enable-browser-proxying:      false
disable-banner:               false
no-request-journal:           false
verbose:                      true
```

### Alpine

1. Run `docker run -it --rm wiremock/wiremock:2.32.0-alpine --verbose`
2. Observe the error in the output:

```
$ docker run --rm -it wiremock/wiremock:2.32.0-alpine --verbose

2022-06-07 17:14:19.608 Verbose logging enabled
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-06-07 17:14:20.223 Verbose logging enabled
 /$$      /$$ /$$                     /$$      /$$                     /$$
| $$  /$ | $$|__/                    | $$$    /$$$                    | $$
| $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
| $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
| $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/
| $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$
| $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
|__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/

port:                         8080
enable-browser-proxying:      false
disable-banner:               false
no-request-journal:           false
verbose:                      true
```

**Comment by rodolpheche** [comment]
This repository only handles Docker packaging of Wiremock standalone jar.

Here is the explanation on why slf4j implementation are not included in the jar : https://github.com/wiremock/wiremock/issues/258#issuecomment-91491412

**Comment by ascopes** [comment]
@rodolpheche The linked issue only addresses the non-standalone JAR, not the standalone one. Those questions went unanswered since 2019, so I am still a little confused.

Should I be opening an issue on the Wiremock repository itself instead? Or is it expected behaviour that the standalone copy needs additional JARs to allow logging to work correctly?

Any advice would be greatly appreciated

**Comment by rodolpheche** [comment]
The explanation is the same for both standalone JAR and not-standalone JAR.

You could ask to @tomakehurst but I think you'll get the same answer : those who want to get technical logs from execution should bring their own slf4j implementation
