### ISSUE TITLE
Multiple extensions

### ISSUE THREAD

**Issue by Haluska77** [wiremock/wiremock-docker#59]
Is there a way to use multiple transformers in '--extensions' option in docker-compose file?
eg:     command: java -cp "/var/wiremock/lib/wiremock-jre8-standalone.jar:/home/wiremock/jar/wiremock-extensions-1.0-SNAPSHOT.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions com.my.extension.TransformerFirst com.my.extension.TransformerSecond

**Comment by rodolpheche** [comment]
As described in the Wiremock documentation (https://wiremock.org/docs/running-standalone/), you can specify multiple exensions by separating class names with a comma:
```
--extensions: Extension class names 
e.g. com.mycorp.HeaderTransformer,com.mycorp.BodyTransformer.
```

Also, you don't need to set the command parameter with the full command as it is wrapped by the entrypoint.
You can do this instead:
```
command: --extensions com.my.extension.TransformerFirst,com.my.extension.TransformerSecond
```
