### ISSUE TITLE
Deploy images to GitHub Container Registry too

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-docker#60]
With all the recent Docker pricing drama and download rate limits for unregistered users & free plans, I think it would be nice to also automate deployments to GitHub Container Registry as a secondary mirror. It can be easily done via GitHub Actions

**Comment by rodolpheche** [comment]
It's now automated

**Comment by ricellis** [comment]
It doesn't seem possible to pull `ghcr.io/wiremock/wiremock` without getting an `unauthorized` error.
AIUI GHCR images are private by default - does it need to be set to `public` [visibility](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#about-setting-visibility-and-access-permissions-for-packages)?
