### ISSUE TITLE
base image needs to be updated

### ISSUE THREAD

**Issue by joshheil** [wiremock/wiremock-docker#64]
### Proposal

According to the documentation for base image used in this project (adoptopenjdk/openjdk11) the image is being deprecated (https://hub.docker.com/_/adoptopenjdk). The recommended steps can be found in the previous link, but can also be found here: https://hub.docker.com/_/eclipse-temurin/

**Comment by mmusenbr** [comment]
The following (unfortunately closed) PR #55  would fix this issue

**Comment by oleg-nenashev** [comment]
> It would be better if https://github.com/wiremock/wiremock-docker/pull/55 could be merged though or better still with java 19 instead!

I believe we should provide an official Java 11/17 images and then the 21 one once released. We need all of them for users, but I agree that the minimum supported version should be kept too.

**Comment by oleg-nenashev** [comment]
@mmusenbr Please check out https://github.com/wiremock/wiremock-docker/releases/tag/2.35.0-1
